### ISSUE TITLE
Tooltip pushes target component down

### ISSUE THREAD

**Issue by nlyle01** [snehilvj/dash-mantine-components#138] opened 2023-01-13 22:35 UTC
Components with a tooltip appear to have extra margin spacing on top compared to components without a tooltip

```python
dmc.Group(
    [
        dmc.Badge("No Tooltip", radius="sm", variant="filled"),
        dmc.Tooltip(
            dmc.Badge("With Tooltip", radius="sm", variant="filled"),
            label="Badge not aligned in Group",
            position="right"
        )
    ]
)
```

![image](https://user-images.githubusercontent.com/50966780/212431505-6784b672-a8d1-4475-9357-b0ec2764e0f1.png)

**Comment by snehilvj** [comment] 2023-01-16 18:09
Hi @nlyle01 I'm not able to reproduce this issue on my end. Can you please share dmc version and the browser you observed this in?
Also it would be helpful if you can share the exact MRE that can be used. It's possible there is some conflicting css in the project.

**Comment by nlyle01** [comment] 2023-01-16 19:30
Maybe it's just me! I'm using DMC version `0.11.0` and dash `2.5.0`. Tested in Chrome and Firefox. Here's what I'm running now to reproduce it:

```python
import dash_mantine_components as dmc
from dash import Dash

app = Dash(__name__)

app.layout = dmc.MantineProvider(
    id="mantine-theme",
    withGlobalStyles=True,
    withNormalizeCSS=True,
    children=[
        dmc.Container(
            children=[
                dmc.Paper(
                    children=[
                        dmc.Group(
                            [
                                dmc.Badge("No Tooltip", radius="sm", variant="filled"),
                                dmc.Tooltip(
                                    dmc.Badge("With Tooltip", radius="sm", variant="filled"),
                                    label="Badge not aligned in Group",
                                    position="right"
                                )
                            ]
                        )
                    ],
                    withBorder=True,
                    p="xl"
                )
            ],
            mt=20
        )
    ],
)

if __name__ == '__main__':
    app.run_server(debug=True)
```

**Comment by nlyle01** [comment] 2023-06-28 22:58
This also seems to happen with `HoverCard`. I'm currently using `dash_mantine_components==0.11.0`.

**Comment by datenzauberai** [comment] 2024-09-08 14:36
This happens because Tooltip wraps its children in a Box. I wonder if this really necessary?

You can workaround this by either wrapping the Badge without a Tooltip in a Box...

```python
dmc.Box(
    dmc.Badge("No Tooltip"),
),
dmc.Tooltip(
    dmc.Badge("With Tooltip"), label="Badge not aligned in Group",
)
```

...or by setting the line height of the wrapping box of the Tooltip to zero:

```python
dmc.Badge("No Tooltip"),
dmc.Tooltip(
    dmc.Badge("With Tooltip"), label="Badge not aligned in Group", boxWrapperProps={"lh": 0}
)
```

<img width="743" alt="Bildschirmfoto 2024-09-08 um 16 34 09" src="https://github.com/user-attachments/assets/f4b2821c-c0e1-4f94-af57-978f66c167de">

**Comment by AnnMarieW** [comment] 2024-09-08 15:17
Hi @datenzauberai 
Nice workaround!  Do you have any ideas for #228 and #296?  I think they are related.

**Comment by datenzauberai** [comment] 2024-09-08 17:35
Indeed you're right. The two can also be solved by setting the boxWrapperProps. I still wonder why the wrapping box is there as it seems to be a real troublemaker 😁

**Comment by AnnMarieW** [comment] 2024-09-08 17:48
Wrapping the Tooltip in the Box component  enables  all  the [dmc style props](https://www.dash-mantine-components.com/style-props) to be applied to the Tooltip.

I'll check with @snehilvj if there is an alternate way to do this, otherwise, I think if this is documented then it should be OK.

**Comment by AnnMarieW** [comment] 2024-09-09 05:36
I opened an [issue](https://github.com/snehilvj/dmc-docs/issues/66) in the dmc-docs, so I'll close this here.

**Closed by AnnMarieW** 2024-09-09 05:36 UTC
