### ISSUE TITLE
Rounding of tooltip number for sliders

### ISSUE THREAD

**Issue by tlienart** [snehilvj/dash-mantine-components#181] opened 2023-04-20 09:45 UTC
Using a slider with floating point steps (e.g. `0.1`) can lead to to numbers that can't be represented exactly and leads to a bunch of decimals being shown e.g.:

<img width="515" alt="Screenshot 2023-04-20 at 11 35 07" src="https://user-images.githubusercontent.com/10897531/233325378-edb4c5b1-72b4-4e92-beb6-7d478f364a81.png">

could there be a parameter added to the Slider to optionally round to x-many decimal places?  I don't know TS but I imagine changing this line https://github.com/snehilvj/dash-mantine-components/blob/1024af5a2940e23e1499c5a00c3129502640bc25/src/ts/components/core/slider/Slider.tsx#L44 to have some form or `Math.round(val, 2)`. 

Thanks

**Comment by hcoohb** [comment] 2023-05-07 12:11
Same issue here

**Comment by snehilvj** [comment] 2023-10-06 19:13
Please share an MRE.

**Comment by datenzauberai** [comment] 2024-09-08 19:57
I can't reproduce this with the current version. Either this was fixed in upstream mantine or the value was injected "unrounded" from a callback. See the following example that initializes the value with 0.30000000004. As soon as you interact with the component it's back to 0.3

```python
from dash import Dash, _dash_renderer
import dash_mantine_components as dmc

_dash_renderer._set_react_version("18.2.0")

app = Dash(external_stylesheets=dmc.styles.ALL)

app.layout = dmc.MantineProvider(
    dmc.Container(
        children=[
            dmc.Space(h="3rem"),
            dmc.Slider(id="slider", min=-1, max=1, step=0.1, value=0.30000000004, style={"width": "100%"})
        ],
    ),
    id="theme-provider",
    forceColorScheme="light"
)

if __name__ == "__main__":
    app.run(debug=True)
```

**Comment by AnnMarieW** [comment] 2024-09-09 05:30
Thanks for the MRE @datenzauberai

**Closed by AnnMarieW** 2024-09-09 05:30 UTC
