### ISSUE TITLE
How to span the entire parent div when wrapping with `Tooltip`?

### ISSUE THREAD

**Issue by guidocioni** [snehilvj/dash-mantine-components#296] opened 2024-08-20 08:12 UTC
I had this problem before with some of the mantine components and couldn't find a clean solution up to now. 
In my app I'm using both dash bootstrap components and dash mantine components. When wrapping a button that spans the entire column width in a `dmc.Tooltip` I cannot preserve this property. 

This is the original button

```python
dmc.Button(className="col-12 mb-2 mt-1", size="xs")
```
which looks like this

![Screenshot 2024-08-20 at 10 08 51](https://github.com/user-attachments/assets/56e6cbd6-88eb-4cb1-ae4b-f9416e80b067)

I tried to wrap it into a `Tooltip` element and using `className` on both elements

```python
dmc.Tooltip(
    children=[dmc.Button(className="col-12 mb-2 mt-1", size="xs")],
    className="col-12 mb-2 mt-1
)
```
however this is not working, as I guess the `className` is only applied to the tooltip element. So the button looks like this

![Screenshot 2024-08-20 at 10 10 32](https://github.com/user-attachments/assets/36132666-52e7-4cfc-b3ee-9c313b26e955)

I tried to wrap it into a `Col` and `Row` wrapper

```python
dbc.Row(
    dbc.Col(
        dmc.Tooltip(
            label="Click to geolocate",
            children=dmc.Button(
                size="xs",
               className="col-12 mb-2 mt-1",
            ),
        ),
        className="col-12 mb-2 mt-1", 
    )
)
```

but I get the same behaviour.

How can I make sure that the styling of the children wrapped in a `Tooltip` is not altered?

**Comment by AnnMarieW** [comment] 2024-08-20 18:15
Hi @guidocioni 

Try adding `fullWidth=True` to the dmc.Button
https://www.dash-mantine-components.com/components/button#full-width-button

**Comment by guidocioni** [comment] 2024-08-21 06:47
> Hi @guidocioni
> 
> Try adding `fullWidth=True` to the dmc.Button https://www.dash-mantine-components.com/components/button#full-width-button
> 
> Plus check out this example of how to use the tooltip with the button https://www.dash-mantine-components.com/components/tooltip#arrow

Hey @AnnMarieW thanks for the answer but unfortunately that doesn't work.
As soon as I wrap the `Button` inside the `Tooltip`, no matter if I'm using `fullWidth=True` or not, it will still revert to the default width (whatever that value is).

I also need to wrap some components coming from bootstrap so the `fullWidth` is not always available. For the moment I'm using `dbc.Tooltip` which seems to work better and doesn't affect the target component (maybe because is not wrapped, so it doesn't really affect its style).

```python
dmc.Button(
    "Geolocate",
    id="geolocate",
    leftSection=DashIconify(icon="ion:location-outline", width=20),
    className="col-12 mb-2 mt-1",
    loaderProps={"type": "dots"},
    size="xs",
    color="gray",
    loading=False,
),
dbc.Tooltip(
    "Use this button to get the current location",
    placement='top',
    target="geolocate",
),
```

**Comment by AnnMarieW** [comment] 2024-08-21 14:48
Hi @guidocioni 

Try running this:

```

import dash_mantine_components as dmc
from dash import Dash, _dash_renderer, html
import dash_bootstrap_components as dbc
_dash_renderer._set_react_version("18.2.0")

app = Dash(external_stylesheets=dmc.styles.ALL+[dbc.themes.BOOTSTRAP])

app.layout = dmc.MantineProvider(
    dmc.Tooltip(
        label="my tootlip",
        children=dmc.Button("my button", size="xs", fullWidth=True),
        className="col-12 mb-2 mt-1 w-100"
    )
)

if __name__ == "__main__":
    app.run(debug=True)


```

**Comment by guidocioni** [comment] 2024-08-22 06:39
> Hi @guidocioni
> 
> Try running this:
> 
> ```python
> import dash_mantine_components as dmc
> from dash import Dash, _dash_renderer, html
> import dash_bootstrap_components as dbc
> _dash_renderer._set_react_version("18.2.0")
> 
> app = Dash(external_stylesheets=dmc.styles.ALL+[dbc.themes.BOOTSTRAP])
> 
> app.layout = dmc.MantineProvider(
>     dmc.Tooltip(
>         label="my tootlip",
>         children=dmc.Button("my button", size="xs", className="col-12 mb-2 mt-1 w-100"),
>         className="col-12 mb-2 mt-1 w-100"
>     )
> )
> 
> if __name__ == "__main__":
>     app.run(debug=True)
> ```

This stretches the button...and the tooltip, so now they both take the whole space :) 

<img width="425" alt="Screenshot 2024-08-22 083405" src="https://github.com/user-attachments/assets/be0c5e02-6721-4a6b-93c3-e857e55a72f4">

I tried your example and I'm seeing the same behaviour, although I'm not including the mantine stylesheet as I'm on 0.14.3 still.

**Comment by AnnMarieW** [comment] 2024-08-22 16:05
Hi @guidocioni 

Yes, I see now - This is a duplicate of https://github.com/snehilvj/dash-mantine-components/issues/228.

It's best to close this one to consolidate the issues

**Closed** 2024-08-22 16:07 UTC

**Comment by datenzauberai** [comment] 2024-09-08 17:18
As @AnnMarieW suspected this can be solved with the `boxWrapperProps`:

```
import dash_mantine_components as dmc
from dash import Dash, _dash_renderer, html
import dash_bootstrap_components as dbc
_dash_renderer._set_react_version("18.2.0")

app = Dash(external_stylesheets=dmc.styles.ALL+[dbc.themes.BOOTSTRAP])

app.layout = dmc.MantineProvider(
    dmc.Container([
        html.Div([
            dbc.Row([
                dbc.Col(html.Div("4", style={"text-align": "center","background-color": "lightgrey"}), className="col-4"),
                dbc.Col(html.Div("8", style={"text-align": "center","background-color": "lightgrey"}), className="col-8")
            ]),
            dbc.Row(
                dmc.Tooltip(
                    label="my tootlip",
                    children=dmc.Button("12", size="xs", className="col-12 mb-2 mt-1 w-100"),
                    boxWrapperProps={"w": "100%"}
                )
            )
        ])
    ])
)

if __name__ == "__main__":
    app.run(debug=True)
```
<img width="940" alt="Bildschirmfoto 2024-09-08 um 19 17 31" src="https://github.com/user-attachments/assets/29987033-e694-4875-8de3-d2ab4feda6aa">

**Comment by AnnMarieW** [comment] 2024-09-08 17:31
@datenzauberai 
This is great! Thanks again for the solution. 
 I'll open an issue to add some examples to the docs
