### ISSUE TITLE
[BUG] dmc.Button fullWidth in dmc.MenuTarget

### ISSUE THREAD

**Issue by OMBeau** [snehilvj/dash-mantine-components#208] opened 2023-10-11 09:25 UTC
The fullWidth option for dmc.Button does not work as intended inside the dmc.MenuTarget wrapper.

```
dmc.Menu(
    [
        dmc.MenuTarget(
            dmc.Button(
                "Test Button",
                fullWidth=True, # Not working as intended within MenuTarget
                ),
            ),
    ]
)
```

**Comment by datenzauberai** [comment] 2024-09-09 20:28
This can not be solved as long as https://github.com/snehilvj/dash-mantine-components/issues/285 is not fixed.

**Comment by AnnMarieW** [comment] 2024-09-12 06:12
Since this is a duplicate of # 285, I'm going to close this now.
Please follow the progress in PR #309   Hopefully it will be in the next release (0.14.5)

**Closed by AnnMarieW** 2024-09-12 06:12 UTC
