### ISSUE TITLE
Debounce boolean in addition to time?

### ISSUE THREAD

**Issue by uns1** [snehilvj/dash-mantine-components#200] opened 2023-08-09 03:13 UTC
Is it possible to have the debounce be a True/False in addition to the current capability of setting a time limit i.e. only consider the input complete once the enter key is hit or if the element loses focus?
Both dash core components and dash bootstrap components have it as a boolean. My text inputs can have high variance and can either be very short or very long so it becomes hard to accurately set a time debounce that works.

**Comment by ZhangPeng4242** [comment] 2024-01-09 13:57
Yes please, I would also like the boolean feature for debounce that Input will only trigger a callback on pressing Enter or losing focus.

**Comment by AnnMarieW** [comment] 2024-09-12 07:40
Hi @jngarber-st , @ZhangPeng4242 @uns1 

Thanks for your feature request.  I’m going to close this because it’s a duplicate of #87.  Please feel free chime in and show your support for this feature  over there.

**Closed by AnnMarieW** 2024-09-12 07:40 UTC
