### ISSUE TITLE
[bug] TagsInput `x` button does not trigger "value" callback

### ISSUE THREAD

**Issue by ctdunc** [snehilvj/dash-mantine-components#369] opened 2024-10-23 13:43 UTC
Hello,
Noticing that when using `TagsInput` removing an item with the delete button in the pill does not trigger callbacks taking the value prop as an input. Deleting it with the keyboard does trigger the callback.

Can be seen [on the dmc documentation website](https://www.dash-mantine-components.com/components/tagsinput).

**Comment by AnnMarieW** [comment] 2024-10-23 14:07
Hi @ctdunc 

Thanks for reporting - I could also replicate the issue in the docs

**Comment by ctdunc** [comment] 2024-10-23 14:54
This may be related to [changes upstream](https://github.com/mantinedev/mantine/pull/6922/files)?

I'm not a JS expert, but I changed the argument of `setValue` from a shallow copy (`.filter(...)`) to a deep copy (`[...values]` after `.splice()`). Maybe has some connection to use as a controlled component? :shrug:

**Comment by ctdunc** [comment] 2024-10-24 15:49
Done a bit more testing, I think this is probably my fault, but I'm not sure how I would go about fixing this upstream.

This is new in 0.14.6 and I think related to [this commit](https://github.com/mantinedev/mantine/pull/6922) (which I authored).

I've spent a bit of time messing with it this morning, but need to move on. Here's what I've found that may help someone with fewer skill issues (or more time) get started: 

* Clicking `x` on a pill triggers `useDidUpdate` for `selected` but not `value`. Deleting a pill with backspace or adding a pill triggers `useDidUpdate` for `selected` and then `value`. For some reason, it looks whatever is passed to `setProps({value: selected})` does not appear to trigger `value` to actually change when using the delete button from a pill.

**Comment by AnnMarieW** [comment] 2024-10-24 22:20
@ctdunc
 dmc 0.14.6 uses Mantine 7.13.2.  
 The changes you made affected which versions of Mantine?  Will the most recent changes fix this issue?

**Comment by ctdunc** [comment] 2024-10-25 16:37
I do not believe the most recent changes fix it. I will have to look more closely once i am not traveling. 

I think I made one of the classic "dont mutate state directly" blunders upstream trying to fix a different issue in the linked PR. unfortunately for whatever reason the mantine build install is blocked on my companies network so i wasnt able to look at work. 

Rolling this back will break the removal of items when duplicates are enabled, but possibly worth?

**Comment by AnnMarieW** [comment] 2024-11-10 21:07
Looks like there is a fix in the works https://github.com/mantinedev/mantine/pull/7105 :tada: 
Thanks @ctdunc !

**Comment by AnnMarieW** [comment] 2024-11-18 23:16
This was fixed in  Mantine 7.14.1.  I just ran the docs locally with the prerelease version of DMC 0.15.0 and confirmed that  it works :partying_face: 

Thanks for your help with this @ctdunc 

Closing now :-)

**Closed by AnnMarieW** 2024-11-18 23:16 UTC
Labels: help wanted, upstream issue
