### ISSUE TITLE
JsonInput formatOnBlur is always on

### ISSUE THREAD

**Issue by revmlx** [snehilvj/dash-mantine-components#211] opened 2023-10-18 07:40 UTC
It seems like the formatOnBlur attribute does not change the behavior of the JsonInput field.

This is what I have in my layout:
```python
dmc.JsonInput(
    id="msa-json-config",
    label="MSA Config",
    placeholder="This component will auto-size to fit the content.",
    validationError="Invalid json",
    formatOnBlur=False,
    autosize=True,
    minRows=4,
)
```

However, each time I exit the JsonInput field, it formats the json text. 

A solution for me would be to either be able to overwrite the format function in JS (but I would need a little help as to how), or being able to disable the formatting from the python object

```
dash_bootstrap_components==1.4.2
dash-extensions==1.0.3
dash-mantine-components==0.12.1
dash-ag-grid==2.3.0
```

**Comment by AnnMarieW** [comment] 2024-09-09 18:28
Hi @revmlx 

I can confirm the issue you reported when running in dmc 0.12.1, but it appears to be fixed in dmc 0.14.4.  

Here is a minimal example using the latest version.
```python
import dash_mantine_components as dmc
from dash import Dash, _dash_renderer, Input, Output, callback, no_update
_dash_renderer._set_react_version("18.2.0")

app = Dash(external_stylesheets=dmc.styles.ALL)

app.layout = dmc.MantineProvider([
    dmc.JsonInput(
        label="Your package.json",
        placeholder="Textarea will autosize to fit the content",
        validationError="Invalid JSON",
        formatOnBlur=False,
        autosize=True,
        minRows=4,
    ),
])

if __name__ == "__main__":
    app.run(debug=True)
```

I'm going to close this for now since I can't replicate the issue with the current version, but feel free to re-open if you have any other questions on this topic.

**Closed by AnnMarieW** 2024-09-09 18:28 UTC
