### ISSUE TITLE
Pressing numpad enter to validate selection on dmc.Select

### ISSUE THREAD

**Issue by A-Wpro** [snehilvj/dash-mantine-components#139] opened 2023-01-16 11:02 UTC
We cannot press numpad enter to validate selection on dmc.Select, that kind of painful for users when your selection is mainly a list of numbers. I am not a expert in TypeScript but I don't think it's will be hard to fix. So if someone can do it it would be a nice feature, else close this issue and I will try to do it by myself and add it with a PR.

Thanks for reading.

**Comment by snehilvj** [comment] 2023-01-16 18:18
I cannot reproduce this issue on my end. I tried it on a Mac and a windows machine. Can you please share an MRE I can use?

Do you see this issue with the Select Menu on the top right of dmc documentation?

<img width="507" alt="Screenshot 2023-01-16 at 11 48 12 PM" src="https://user-images.githubusercontent.com/91216500/212743859-62da9ab1-20dc-4b6f-b25f-94d243060ae8.png">

**Comment by A-Wpro** [comment] 2023-01-20 13:02
I don't have this issues with the docs's dmc.Select component. 
But on this MRE, I have this issues once again : 


          from dash import Dash, html
          import dash_mantine_components as dmc
          from flask import Flask
          server = Flask(__name__)
          app = Dash(__name__, server=server, prevent_initial_callbacks=True)
          app.title = "MRE"
          input_bar = dmc.Stack(
              children=[
                  dmc.Select(id="wellnameinput", placeholder="Enter Well Name:", rightSection=[
                  ], data=["A", "B", "C"], searchable=True, style={"width": "200", "color": "#FFFFFF"},)
              ], style={"position": "relative", "top": "20px", "display": "flex", "flexDirection": "row", "boxAlign": "stretch", "alignItems": "flex-end", "fontFamily": "Roboto,Helvetica,Arial,sans-serif", "marginBottom": "30px"}
          )
          app.layout = dmc.NotificationsProvider([html.Div([
              dmc.Container([
                  html.Div(
                      [
                          html.Div([
                              input_bar
                          ])])
              ]),
          ]),
          ])
          if __name__ == '__main__':
              app.run_server(host="0.0.0.0")

Thanks for you answers

**Comment by A-Wpro** [comment] 2023-05-01 09:15
bump/I still got the issue.

**Comment by datenzauberai** [comment] 2024-09-11 20:37
I can't reproduce this with the latest version:

```
from dash import Dash, _dash_renderer, html
import dash_mantine_components as dmc

_dash_renderer._set_react_version("18.2.0")

app = Dash(external_stylesheets=dmc.styles.ALL)

app.layout = dmc.MantineProvider(
    dmc.Container([
        dmc.NotificationProvider(),
        html.Div([
            dmc.Container([
                html.Div([
                    html.Div([
                        dmc.Stack(children=[
                            dmc.Select(
                                id="wellnameinput",
                                placeholder="Enter Well Name:",
                                rightSection=[],
                                data=["A", "B", "C"],
                                searchable=True,
                                style={
                                    "width": "200",
                                    "color": "#FFFFFF",
                                },
                            )],
                            style={
                                "position": "relative",
                                "top": "20px",
                                "display": "flex",
                                "flexDirection": "row",
                                "boxAlign": "stretch",
                                "alignItems": "flex-end",
                                "fontFamily": "Roboto,Helvetica,Arial,sans-serif",
                                "marginBottom": "30px",
                            },
                        )
                    ])
                ])
            ]),
        ]),
    ], style={"padding": "1rem"}),
    id="theme-provider",
    forceColorScheme="light",
)

if __name__ == "__main__":
    app.run(debug=True)
```

**Comment by AnnMarieW** [comment] 2024-09-12 04:15
Since we are unable to reproduce this issue, I'm closing it for now.  If anyone can provide the steps to take to consistently demonstrate this issue, please feel free to re-open.

Thanks @datenzauberai  for investigating. :slightly_smiling_face:

**Closed by AnnMarieW** 2024-09-12 04:15 UTC
