### ISSUE TITLE
[BUG] dmc.HoverCard blocked by other components when placed in a dmc.AccordionMultiple with style={'postion': ‘fixed’} set.

### ISSUE THREAD

**Issue by Kevinckyy** [snehilvj/dash-mantine-components#222] opened 2024-01-10 11:48 UTC
Hello! I met a bug about `dmc.Hovercard`, it will be blocked by most components (except components like `dmc.Text` )when placed in a position-fixed `dmc.AccordionMultiple` component. Screenshot and a minimal app were listed below:
 
![image](https://github.com/snehilvj/dash-mantine-components/assets/44802223/d8582145-4ac8-4f92-8a7a-3489c576a11e)

```python

from dash import dcc
import dash_mantine_components as dmc
from dash_extensions.enrich import DashProxy
from dash_iconify import DashIconify

app = DashProxy()

app.layout = dmc.Grid(
  [
    dmc.Col(
      [
        dmc.AccordionMultiple(
          [
            dmc.AccordionItem([
              dmc.AccordionControl('test'),
              dmc.AccordionPanel([
                dmc.HoverCard(
                  openDelay=200,
                  # position='right',
                  children=[
                    dmc.HoverCardTarget(
                      dmc.ActionIcon(
                        DashIconify(icon = 'akar-icons:circle-fill', color='#fa5252', width=48),
                        variant='transparent', mt=3
                      )
                    ),
                    dmc.HoverCardDropdown([
                      dmc.ColorPicker(format='hex', value='#fa5252'),
                      dmc.TextInput(value='#fa5252'),
                    ]),
                  ],
                )
              ]),
            ], value='test')
          ],
          style={'position': 'fixed', 'width': '40vh'},
        ),
      ],
      span=2
    ),
    dmc.Col(
      [
        dcc.Graph(figure={}),
        dmc.Text('This is a `dmc.Text` component'),
        dmc.RangeSlider(),
        dcc.Graph(figure={})
      ],
      span=10
    )
  ]
)

app.run_server()
```

**Comment by RainyBlue-w** [comment] 2024-01-10 12:14
I have also met this BUG ! Wish someone could figure out what happened and solve it ... 😢

**Comment by CNFeffery** [comment] 2024-01-10 13:29
@Kevinckyy @RainyBlue-w  Components with similar functionality: https://fac.feffery.tech/AntdPopover

**Comment by RainyBlue-w** [comment] 2024-01-10 13:56
> @Kevinckyy @RainyBlue-w Components with similar functionality: https://fac.feffery.tech/AntdPopover

 Thank you! I have tried the fac, it's a wonderful package, but the problem can only be partially solved. When I set `popupContainer = 'parent' `, the same bug occured. This is the code:

```python
from dash import html
from dash import dcc
import dash_mantine_components as dmc
import feffery_antd_components as fac
from dash_extensions.enrich import DashProxy
from dash_iconify import DashIconify

app = DashProxy()

app.layout = dmc.Grid(
  [
    dmc.Col(
      [
        html.Span(
          dmc.AccordionMultiple(
            [
              dmc.AccordionItem([
                dmc.AccordionControl('test'),
                dmc.AccordionPanel([
                  fac.AntdPopover(
                    children=[
                      dmc.ActionIcon(
                        DashIconify(icon = 'akar-icons:circle-fill', color='#fa5252', width=48),
                        variant='transparent', mt=3
                      )
                    ],
                    content =[
                        dmc.ColorPicker(format='hex', value='#fa5252'),
                        dmc.TextInput(value='#fa5252'),
                    ],
                    popupContainer = 'parent'
                  ),
                ]),
              ], value='test')
            ],
          ),
          style={'position': 'fixed', 'width': '40vh'},
        ),
      ],
      span=2
    ),
    dmc.Col(
      [
        dcc.Graph(figure={}),
        dmc.Text('This is a `dmc.Text` component'),
        dmc.RangeSlider(),
        dcc.Graph(figure={})
      ],
      span=10
    )
  ]
)
```

**Comment by RainyBlue-w** [comment] 2024-01-10 14:31
> @Kevinckyy why set `popupContainer = 'parent'`, it only used in some special layout.

Because I want to let the hoverCard rolling with it's target

**Comment by CNFeffery** [comment] 2024-01-10 14:38
> > @Kevinckyy why set `popupContainer = 'parent'`, it only used in some special layout.
> 
> Because I want to let the hoverCard rolling with it's target

Since your `AntdPopover` is within a fixed element, a fixed means it won't be rolled by scrolling in the current page.🤔

**Comment by RainyBlue-w** [comment] 2024-01-10 15:01
> > > @Kevinckyy why set `popupContainer = 'parent'`, it only used in some special layout.
> > 
> > 
> > Because I want to let the hoverCard rolling with it's target
> 
> Since your `AntdPopover` is within a fixed element, a fixed element means it won't be rolled by scrolling in the current page.🤔

You could try to run the code, when I roll on the right, the hoverCard will also be rolling if I down't set popupContainer

**Comment by CNFeffery** [comment] 2024-01-11 02:06
@RainyBlue-w 
Because your AntdPopover is bound within a container that has a fixed layout, achieving a perfect balance is not possible. However, when the mouse moves out of the AntdPopover area, it will automatically close by default. Therefore, there is no need to worry about the specific scenario of moving the mouse to the right area and scrolling.

**Comment by RainyBlue-w** [comment] 2024-01-11 13:37
@CNFeffery  Thank you, I have understand it! Now I'm using fac instead of dmc to build my hoverCard, fac is really a useful components package!

**Comment by AnnMarieW** [comment] 2024-09-15 12:53
@Kevinckyy and @RainyBlue-w 

Just wanted to let you know that this is fixed in the latest version of dmc.  The example below is using 0.14.4

Since I can't reproduce the issue and it looks like you found an alternate solution, I'll close this now.  Please feel free to re-open if you have any follow-up questions

```python
from dash import Dash, dcc, _dash_renderer
import dash_mantine_components as dmc
from dash_iconify import DashIconify

_dash_renderer._set_react_version("18.2.0")

app = Dash(external_stylesheets=dmc.styles.ALL)

app.layout = dmc.MantineProvider(
    dmc.Grid(
        [
            dmc.GridCol(
                [
                    dmc.Accordion(
                        [
                           dmc.AccordionItem(
                                [
                                    dmc.AccordionControl("test"),
                                    dmc.AccordionPanel(
                                        [
                                            dmc.HoverCard(
                                                openDelay=200,
                                                # position='right',
                                                children=[
                                                    dmc.HoverCardTarget(
                                                        dmc.ActionIcon(
                                                            DashIconify(
                                                                icon="akar-icons:circle-fill",
                                                                color="#fa5252",
                                                                width=48,
                                                            ),
                                                            variant="transparent",
                                                            mt=3,
                                                        )
                                                    ),
                                                    dmc.HoverCardDropdown(
                                                        [
                                                            dmc.ColorPicker(
                                                                format="hex",
                                                                value="#fa5252",
                                                            ),
                                                            dmc.TextInput(
                                                                value="#fa5252"
                                                            ),
                                                        ]
                                                    ),
                                                ],
                                            )
                                        ]
                                    ),
                                ],
                                value="test",
                            )
                        ],
                        style={"position": "fixed", "width": "40vh"},
                        chevronPosition="left"
                    ),
                ],
                span=2,
            ),
            dmc.GridCol(
                [
                    dcc.Graph(figure={}),
                    dmc.Text("This is a `dmc.Text` component"),
                    dmc.RangeSlider(),
                    dcc.Graph(figure={}),
                ],
                span=10,
            ),
        ]
    )
)

if __name__ == "__main__":
    app.run_server(debug=True)

```

![dmc-hovercard-in-accordion](https://github.com/user-attachments/assets/f2bd467c-b8e7-4f81-92be-0333299a2408)

**Closed by AnnMarieW** 2024-09-15 12:53 UTC
