### ISSUE TITLE
trying to use MultiSelect in a Modal. No values show in dropdown

### ISSUE THREAD

**Issue by blanning19** [snehilvj/dash-mantine-components#80] opened 2022-06-16 19:58 UTC
Hello, I am trying to implement a Multiselect object in a modal but when I open the modal, none of the values show.
Is this a known issue or am I doing this wrong?

Here is my modal code. I tested it and it works in my main form, but not in a modal:
```python
            dbc.ModalBody(
                id="value_picker_modal_body",
                children=[
                    dmc.MultiSelect(
                        label="Select 3D-axis plot variables:",
                        id="selected-3d-attr",
                        value=[],
                        data=[
                            {"value": "parameter1", "label": "Parameter1"},
                            {"value": "parameter2", "label": "Parameter2"},
                            {"value": "attribute1", "label": "Attribute1"},
                            {"value": "attribute2", "label": "Attribute2"},
                        ],
                        creatable=True,
                        clearable=True,
                    ),
                ],
                style={"height": "60vh", "overflow": "scroll"},

            )
```
The result is when I click in the dropdown on the modal window, nothing happens.
Is there a parameter I need to make it run in a modal window?

Thanks.

**Comment by snehilvj** [comment] 2022-06-17 12:26
Hi @blanning19
Can you share an MRE? I run this code and see now issues.

```python
import dash_mantine_components as dmc
import dash_bootstrap_components as dbc

from dash import html, Output, Input, State, callback, Dash

app = Dash(__name__)

app.layout = html.Div(
    [
        dmc.Button("Open Modal", id="modal-demo-button"),
        dbc.Modal(
            id="modal",
            children=[
                dmc.MultiSelect(
                    label="Select 3D-axis plot variables:",
                    id="selected-3d-attr",
                    value=[],
                    data=[
                        {"value": "parameter1", "label": "Parameter1"},
                        {"value": "parameter2", "label": "Parameter2"},
                        {"value": "attribute1", "label": "Attribute1"},
                        {"value": "attribute2", "label": "Attribute2"},
                    ],
                    creatable=True,
                    clearable=True,
                )
            ],
            style={"height": "60vh", "overflow": "scroll"},
        ),
    ]
)


@callback(
    Output("modal", "is_open"),
    Input("modal-demo-button", "n_clicks"),
    State("modal", "is_open"),
    prevent_initial_call=True,
)
def modal_demo(nc1, is_open):
    return not is_open


if __name__ == "__main__":
    app.run_server(debug=True)
```

**Comment by blanning19** [comment] 2022-06-17 13:17
Hello!
Thank you for your quick response.

So I need to have multiple MultiSelects. For this example I just duplicated
you MultiSelect:

app.layout = html.Div(
    [
        dmc.Button("Open Modal", id="modal-demo-button"),
        dbc.Modal(
            id="modal",
            children=[
                dmc.MultiSelect(
                    label="Select 3D-axis plot variables:",
                    id="selected-3d-attr",
                    value=[],
                    data=[
                        {"value": "parameter1", "label": "Parameter1"},
                        {"value": "parameter2", "label": "Parameter2"},
                        {"value": "attribute1", "label": "Attribute1"},
                        {"value": "attribute2", "label": "Attribute2"},
                    ],
                    creatable=True,
                    clearable=True,
                ),
                dmc.MultiSelect(
                    label="Select 3D-axis plot variables2:",
                    id="selected-3d-attr2",
                    value=[],
                    data=[
                        {"value": "parameter1", "label": "Parameter1"},
                        {"value": "parameter2", "label": "Parameter2"},
                        {"value": "attribute1", "label": "Attribute1"},
                        {"value": "attribute2", "label": "Attribute2"},
                    ],
                    creatable=True,
                    clearable=True,
                )


            ],
            style={"height": "60vh", "overflow": "scroll"},
        ),
    ]
)

The bottom most MultiSelect does display values, but it looks disabled? I
might be able to fix with some css but not sure.

[image: image.png]

However the top dropdown does not show all of the values. Like they are
behind the bottom MultiSelect:
[image: image.png]

For my modal I may have up to 7 or 8 MultiSelects.

Any ideas?

Brad

**Comment by snehilvj** [comment] 2022-06-17 17:44
Can you share the screenshots again. Don't think they were attached successfully here.

**Comment by blanning19** [comment] 2022-06-17 21:10
Hi, here are the two images as attachments.
Thanks!

**Comment by blanning19** [comment] 2022-06-23 15:41
Hello.
I wanted to ask one more time if you had any luck with this.

I would rather use your tool than the dcc.Dropdown but it is working on the
modal for me.

Brad

**Comment by blanning19** [comment] 2022-06-24 03:34
Hello.
 Have you tried more than one drodown in a modal?
Here is the code

app.layout = html.Div(
    [
        dmc.Button("Open Modal", id="modal-demo-button"),
        dbc.Modal(
            id="modal",
            children=[
                dmc.MultiSelect(
                    label="Select 3D-axis plot variables:",
                    id="selected-3d-attr",
                    value=[],
                    data=[
                        {"value": "parameter1", "label": "Parameter1"},
                        {"value": "parameter2", "label": "Parameter2"},
                        {"value": "attribute1", "label": "Attribute1"},
                        {"value": "attribute2", "label": "Attribute2"},
                    ],
                    creatable=True,
                    clearable=True,
                ),
                dmc.MultiSelect(
                    label="Select 3D-axis plot variables2:",
                    id="selected-3d-attr2",
                    value=[],
                    data=[
                        {"value": "parameter1", "label": "Parameter1"},
                        {"value": "parameter2", "label": "Parameter2"},
                        {"value": "attribute1", "label": "Attribute1"},
                        {"value": "attribute2", "label": "Attribute2"},
                    ],
                    creatable=True,
                    clearable=True,
                )


            ],
            style={"height": "60vh", "overflow": "scroll"},
        ),
    ]
)


This does not work

the top dropdown appear to be hidden behind the dropdown below it.
So by the time I do 3 or 4 dropdowns, the values are completely hidden
behind the dropdown above them

I have attached the images directly and as attachments
How would you prefer to see them?
Top dropdown. (I can't see the top 2 values in the dropdown)

[image: image.png]

2nd dropdown( I can see all values but hey are greyed out lik the are
disabled)

[image: image.png]

**Comment by AnnMarieW** [comment] 2022-06-26 16:42
Hi @blanning19 

When posting an issue, it's important to include a _complete_ minimal example that can be copied, pasted, and run by someone else to reproduce the error you are seeing.  For more info on how to do this, see the Dash Community forum post - [How to get your questions answered on the forum](https://community.plotly.com/t/how-to-get-your-questions-answered-on-the-plotly-forum/40551).  It would also be good to post your question on the forum first, in case it's just a "how-to" issue and not a bug.

Also here's more info on how to [include files and images](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files) in a GitHub issue or pull request.

In this case, I can replicate what you are seeing.  The issue looks like the dropdown options are behind the modal.  This can be fixed by using the `zIndex` prop.  Here's what the example code posted below looks like with the `zIndex` prop commented out.

![dmc_dropdown](https://user-images.githubusercontent.com/72614349/175824488-3f16f82a-2943-432d-8329-2e94af4dfd1a.gif)


Here's an image of the working dropdown - just make the `zIndex` prop not commented out in the example below
![image](https://user-images.githubusercontent.com/72614349/175824216-90ed5ff1-c836-46eb-8584-55b61500a0bb.png)




```python

from dash import Dash, html
import dash_bootstrap_components as dbc
import dash_mantine_components as dmc

app = Dash(__name__, external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = html.Div(
    [
        dmc.Button("Open Modal", id="modal-demo-button"),
        dbc.Modal(
            id="modal",
            children=[
                dmc.MultiSelect(
                    label="Select 3D-axis plot variables:",
                    id="selected-3d-attr",
                    value=[],
                    data=[
                        {"value": "parameter1", "label": "Parameter1"},
                        {"value": "parameter2", "label": "Parameter2"},
                        {"value": "attribute1", "label": "Attribute1"},
                        {"value": "attribute2", "label": "Attribute2"},
                    ],
                    creatable=True,
                    clearable=True,
                    zIndex=2000

                ),
                dmc.MultiSelect(
                    label="Select 3D-axis plot variables2:",
                    id="selected-3d-attr2",
                    value=[],
                    data=[
                        {"value": "parameter1", "label": "Parameter1"},
                        {"value": "parameter2", "label": "Parameter2"},
                        {"value": "attribute1", "label": "Attribute1"},
                        {"value": "attribute2", "label": "Attribute2"},
                    ],
                    creatable=True,
                    clearable=True,
                    zIndex=2000
                )


            ],
            style={"height": "60vh", "overflow": "scroll"},
            is_open=True
        ),
    ],
)


if __name__ == '__main__':
     app.run_server(debug=True)

```


```

**Comment by blanning19** [comment] 2022-06-26 22:36
Thank you!

The zindex setting seems to have fixed the problem. !!

**Comment by snehilvj** [comment] 2022-06-27 17:07
Thanks @AnnMarieW

**Closed by snehilvj** 2022-06-27 17:07 UTC
