### ISSUE TITLE
Debounce not working for dmc.Select and dmc.MultiSelect

### ISSUE THREAD

**Issue by chen-hui-long** [snehilvj/dash-mantine-components#194] opened 2023-07-13 01:58 UTC
Hi, debounce does not seems to work for these components, the callback is fired immediately despite `debounce=2000`

**Comment by benweinberg89** [comment] 2024-08-04 03:45
+1 to please implement debounce for dmc.MultiSelect or a simple workaround that doesn't add an extra button/callback.

**Comment by AnnMarieW** [comment] 2024-09-12 07:53
Hi @chen-hui-long @benweinberg89, @vhasik 

Thanks for reporting.  I'm going to close this for now since it's a duplicate of #87 

Please feel free to add comments and up-vote this feature over there.

**Closed by AnnMarieW** 2024-09-12 07:53 UTC
