### ISSUE TITLE
Problem with TimeInput Component

### ISSUE THREAD

**Issue by adubey14** [snehilvj/dash-mantine-components#175] opened 2023-04-11 13:51 UTC
The timeinput component on Chrome (version 0.12.1) gives an exception in the javascript on g.getTime is not a function. This error is coming from react which is being used behind the scenes. I have not looked at the complete logic of the javascript -- so I dont know if the type g is actually not a date in this case. Any help will be appreciated.

react-dom@16.v2_8_1m1678455914.14.0.min.js:125 TypeError: g.getTime is not a function
    at dash_mantine_components.v0_12_1m1681220069.js:2:528019
    at dash_mantine_components.v0_12_1m1681220069.js:2:554053
    at Bh (react-dom@16.v2_8_1m1678455914.14.0.min.js:126:456)
    at Dj (react-dom@16.v2_8_1m1678455914.14.0.min.js:162:476)
    at unstable_runWithPriority (react@16.v2_8_1m1678455914.14.0.min.js:25:260)
    at Da (react-dom@16.v2_8_1m1678455914.14.0.min.js:60:280)
    at xb (react-dom@16.v2_8_1m1678455914.14.0.min.js:162:231)
    at Te (react-dom@16.v2_8_1m1678455914.14.0.min.js:146:79)
    at react-dom@16.v2_8_1m1678455914.14.0.min.js:61:68
    at unstable_runWithPriority (react@16.v2_8_1m1678455914.14.0.min.js:25:260)

**Comment by AnnMarieW** [comment] 2024-09-10 05:15
I'm unable to reproduce this error in either V12 or V14, so I'm going to close this issue for now.

https://www.dash-mantine-components.com/components/timeinput
https://dmc-docs-0-12.onrender.com/components/timeinput


@adubey14 if this is still a problem, feel free to re-open this issue and please include a complete minimal example that reproduces the error.

**Closed by AnnMarieW** 2024-09-10 05:15 UTC
