### ISSUE TITLE
DateRangePicker makes application freeze

### ISSUE THREAD

**Issue by andresballenf** [snehilvj/dash-mantine-components#180] opened 2023-04-19 22:37 UTC
DateRangePicker makes application freeze if you click on inmediatly after it's render in the page

**Comment by gofford** [comment] 2023-05-05 10:02
I have this same issue. 

I first noticed it on a personal app so had assumed it was (possibly) a local CSS conflict. But it also happens on the native docs webapp. It's both `DatePicker` and `DateRangePicker`, and is somewhat sporadic.

I can reproduce it with 30-40% confidence by:

- going to https://www.dash-mantine-components.com/components/datepicker
- clicking any DatePicker quite quickly after load
- Sometimes, no popover shows and eventually my browser tab times out.

Video of the behaviour (happened in 3rd refresh):

https://user-images.githubusercontent.com/32452466/236429279-16e3a3ae-a2f6-48a6-ac1a-e4fa89caca9f.mov

I've been unable to track down the cause, but in a local app the locking happens 100% of the time when the DatePicker is used within a modal. 

It's a behaviour specific to 0.12 and it didn't happen in 0.11.x

**Comment by snehilvj** [comment] 2023-05-06 08:16
Thanks @andresballenf for creating this issue and @gofford for the analysis. I'm on it.

**Comment by snehilvj** [comment] 2023-05-06 08:34
I'm able to reproduce this issue on the docs too but not even once in isolation.

**Comment by andresballenf** [comment] 2023-05-29 20:43
Hi @snehilvj thanks for investigating this. Is there any solution? Should we wait until Mantine fix it?

**Comment by MireilleMedhat** [comment] 2023-06-15 21:00
Hello, we are currently facing the same issue in our app, any updates on this?

**Comment by snehilvj** [comment] 2023-06-17 04:01
Hi not yet. The only way for now is to use a 0.11 release.

**Comment by jbetley** [comment] 2023-09-14 16:47
Can confirm that this affects HoverCard (thank goodness I found this thread, I was pulling my hair out). Am mitigating the issue by setting the position to "bottom" and ensuring that there is always enough of a margin at the bottom of the page.

Also, It has been 3 months, any update?

**Comment by snehilvj** [comment] 2023-10-07 04:57
This has been fixed in the latest 0.13 alphas.

**Closed by snehilvj** 2023-10-07 04:57 UTC
