### ISSUE TITLE
RangeSlider bold (and maybe larger) text for min 0

### ISSUE THREAD

**Issue by tristanryerparke** [snehilvj/dash-mantine-components#191] opened 2023-06-28 16:24 UTC
For some reason when creating a RangeSlider with min 0 and marks at 0, the lefthand label appears bold, potentially a larger font and off-center:

![Screenshot 2023-06-28 at 12 22 50 PM](https://github.com/snehilvj/dash-mantine-components/assets/57774376/e3ee5a44-dbe3-4534-954f-66bf9f2adaab)

however when min is set to 1 or another value, it appears normally:

![Screenshot 2023-06-28 at 12 23 51 PM](https://github.com/snehilvj/dash-mantine-components/assets/57774376/86b5cc46-e5e4-417e-9a30-69913e25463f)

here is the code to to to reproduce:
```
dmc.RangeSlider(
  value=[5, 15],
  id='test_slider',
  min=0,
  max=20,
  minRange=1,
  maxRange=20,
  step=0.1,
  marks=[{'value': min, 'label': min}, {'value': max, 'label': max}],
  precision=2,
  style={'width': '100%'},
)

**Comment by datenzauberai** [comment] 2024-09-08 20:48
I checked in the upstream Mantine library (v7.12.2) and it happens there as well. Anyway the label should be a string, not a number. If you label it with "0" instead of 0 it's all good:

<img width="995" alt="Bildschirmfoto 2024-09-08 um 22 46 04" src="https://github.com/user-attachments/assets/898a7afc-44fe-4d83-b9f9-5c9b670e8692">

```python
from dash import Dash, _dash_renderer
import dash_mantine_components as dmc

_dash_renderer._set_react_version("18.2.0")

app = Dash(external_stylesheets=dmc.styles.ALL)

app.layout = dmc.MantineProvider(
    dmc.Container(
        children=[
            dmc.Space(h="3rem"),
            dmc.Code('{"value": 0, "label": 0}'),
            dmc.RangeSlider(
                id="int_label",
                marks=[{"value": 0, "label": 0}, {"value": 100, "label": 100}],
                style={"width": "100%"},
            ),
            dmc.Space(h="3rem"),
            dmc.Code('{"value": 0, "label": str(0)}'),
            dmc.RangeSlider(
                id="str_label",
                marks=[{"value": 0, "label": str(0)}, {"value": 100, "label": str(100)}],
                style={"width": "100%"},
            ),
            dmc.Space(h="3rem"),
            dmc.Code('{"value": 0, "label": dmc.Text(0, size="sm")}'),
            dmc.RangeSlider(
                id="text_label",
                marks=[{"value": 0, "label": dmc.Text(0, size="sm")}, {"value": 100, "label": dmc.Text(100, size="sm")}],
                style={"width": "100%"},
            )
        ],
    )
)

if __name__ == "__main__":
    app.run(debug=True)
```

I would suggest to close this issue and someone might want to file an issue with upstream Mantine.

**Comment by AnnMarieW** [comment] 2024-09-09 05:29
Thanks for a good workaround @datenzauberai .  I agree the issue is with the upstream Mantine, so I'll close this here.

**Closed by AnnMarieW** 2024-09-09 05:29 UTC
